"use strict";
exports.__esModule = true;
var punto_1 = require("./punto");
var coordenadas = new punto_1.Punto(2, 2);
var coordenadas2 = new punto_1.Punto(2, 4);
var conjuntocoordenadas = [coordenadas, coordenadas2];
coordenadas.setX(3);
coordenadas.setY(3);
coordenadas.getX();
coordenadas.getY();
console.log(coordenadas.distanciaAlOrigen());
console.log(coordenadas.calcularDistancia(new punto_1.Punto(2, 3)));
console.log(coordenadas.calcularCuadrante());
calcularMasCercano(conjuntocoordenadas);
